### ISSUE TITLE
Problem: how do we compile PHP?

### ISSUE THREAD

**Issue by alexbuzzbee** [PyHP-pph/PyHP_pph#13]
If the CIC is supposed to be the *compiled* interpreter-compiler, how will we compile it if it's written in PHP, an interpreted language?

**Comment by Boscillator** [comment]
I thought it was the compiler-interpreter-compiler, in that it compiles PyHP++# into the half compiled, half interpreted state.

**Comment by alexbuzzbee** [comment]
That seems... odd. It also wouldn't work outside of a JIT compiler, and I don't think anyone here wants to write an entire JIT compiler.

**Comment by Boscillator** [comment]
What if by compiled we meant compiled to byte code, or perhaps, transpiled. While not technically compiled, this option would be easier.

There also appears to be libraries for JITing, of course.

**Comment by alexbuzzbee** [comment]
Ehhhh, I don't know if we want to go to the effort of building a transpiler/bytecode compiler for PHP just so we can build a compiler/interpreter for a different language.

**Comment by alexbuzzbee** [comment]
Maybe it should just be a totally inappropriate name.

**Comment by Boscillator** [comment]
It doesn't need to be a bytecode compiler for PHP, we could invent the bytecode language. I also have some experience targeting python byte code, so that could be fun.

**Comment by alexbuzzbee** [comment]
If you want to write one, go ahead!

**Comment by DyingEcho** [comment]
I don't know much PHP, but it looks like there's a [PHP compiler here](https://github.com/devsense/phalanger/). @alexbuzzbee was right - it is _Compiled Interpreter-Compiler_.

**Comment by DyingEcho** [comment]
See also [this](https://www.reddit.com/r/PyHP_pph/wiki/lang/run) and [this](https://www.reddit.com/r/PyHP_pph/comments/6h22z9/suggestion_megathread/diuvato/).

**Comment by Ulfr26** [comment]
Can someone explain how a compiled interpreter-compiler would work?

**Comment by boynedmaster** [comment]
You write a program that interprets and compiles PyHP++# (perhaps to bytecode) and then you compile that program.
