### ISSUE TITLE
template.md does not conform with anything else, or the PyHP++# 'look+feel'

### ISSUE THREAD

**Issue by DyingEcho** [PyHP-pph/PyHP_pph#15]
The specification document 'template.md' does not conform with anything else, nor does it take obvious inspiration from any of the Inspiration Languages. It is indeed a masterpiece - but I don't feel that it belongs here.

**Comment by Boscillator** [comment]
My idea with the template language was to start with something that doesn't sound to bad, a very simple yet powerful meta-programming tool, and then go about implementing it horribly. It's designed to allow a programmer to maximally mess up there program, and to be unmaintainable as possible. In that light it does fit in with PyHP++#.

**Comment by boynedmaster** [comment]
It could be argued the templates are a bastardized version of inline PHP.

**Comment by alexbuzzbee** [comment]
And it is somewhat similar in general concept to C++'s templates.
