### ISSUE TITLE
Add spec for comments. 

### ISSUE THREAD

**Issue by boynedmaster** [PyHP-pph/PyHP_pph#18]
Single line comments are already established in example code as starting with //#* .

I say we take after Python, and not have official multi-line comments at all. Whether we allow multi-line strings (a la Python) or just tell programmers to use multiple single comments is up to the committee.

**Comment by Boscillator** [comment]
I think you should go ahead an add single-line comments to the spec. We can always edit the file to allow multi-line if we feel it's necessary.

**Comment by boynedmaster** [comment]
Sounds good, I will form a document for this now.
