### ISSUE TITLE
"Hello, world" example on template.md contradicts rest of spec.

### ISSUE THREAD

**Issue by boynedmaster** [PyHP-pph/PyHP_pph#36]
https://github.com/PyHP-pph/PyHP_pph/blob/master/spec/template.md#hello-world-example

template.md repeatedly refers to a stack. In the example given:

```
<hello>
<world>

<.> <.>
```

The stack would be (before `<.> <.>`):
- world
- hello

Thus when doing `<.> <.>` it should be "world hello". Assuming I'm not misunderstanding, the example should instead be:

```
<world>
<hello>

<.> <.>
```

**Comment by Boscillator** [comment]
Yah, your right. I'll fix that.
