### ISSUE TITLE
Parser implementation

### ISSUE THREAD

**Issue by as-com** [PyHP-pph/PyHP_pph#7]
Although the standard is yet to be finalized, ratified, and certified by the Committee, given the suggestions and ideas floating around, I expect that this language is going to be horrendously difficult to parse.

It appears that [nearley](http://nearley.js.org) would be a good fit for parsing such a language, so our first PyHP++# interpreter would be referred to as "PyHP_pph.js". Any thoughts?

**Comment by alexbuzzbee** [comment]
Horrifyingly, we've already made the decision that the compiler-interpreter-compiler has to be written in PHP.

**Comment by alexbuzzbee** [comment]
It's not finalized, so we could drop it in favor of having `PyHP_pph.js`

**Comment by Boscillator** [comment]
If we do desire to force people to write the cic in PHP, I found [this library](https://github.com/farafiri/PHP-parsing-tool) for parsing grammar in php. However, I agree, we should remove the php requirement. No actual language spec specifies and implementation language, and we want to make this look as serous and official as possible.

**Comment by PumpkinSeed** [comment]
Maybe in Golang?

**Comment by DyingEcho** [comment]
I think nearley would be a good idea, it will make things easier for us (even though JS is just as stupid an idea for a CIC as PHP). I also agree with @Boscillator that no actual language spec specifies implementation language, however there's nothing wrong with being first :)

**Comment by PryDt** [comment]
I would prefer Goland or JS for the interpreter, just so we will be able to make it faster, and with more libraries / support.

**Comment by boynedmaster** [comment]
I just got a lot of work done on my CIC written in Python 3, [here](https://github.com/boynedmaster/PyHP-PPH.py). It hasn't fully implemented the spec and has a lot of warnings for things not yet implemented in the spec, but it's the first working CIC so far.

**Comment by DyingEcho** [comment]
We should allow multiple. The CIC developers should be able to choose the language that they work in. This means:

a) Everyone is happy with the language they're in, and
b) There are multiple CICs in varying stages of completion - this makes things much harder for the programmer, especially if the CICs themselves don't have documented support for each part of the specs.

**Comment by DyingEcho** [comment]
As long as they are run in a WinXP VM on WinXP everything should be fine.
